config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'pages#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :tournaments, only: [:index, :show] do
    put 'register_player'
  end
  resources :streams, only: [:index]
  resources :articles, only: [:index, :show]

  namespace :dashboard do
    resources :tournaments, only: [:index, :show]
  end

  namespace :editor do
    resources :articles
    resources :tournaments
  end

  resources :likes, only: [:create]
  resources :dislikes, only: [:create]
  resources :comments, only: [:create]

  mount Thredded::Engine => '/forum'

  get 'contacts', to: 'pages#contacts'
  get 'profile/:slug', to: 'profiles#show', as: :profile
end

app/models/article.rb
class Article < ApplicationRecord
  default_scope { order('id DESC') }
  
  scope :sorted_by_likes, -> { unscoped.all.includes(:comments).sort {|a, b| b.rating <=> a.rating } }

  extend FriendlyId
  friendly_id :title, use: :slugged

  has_many :comments

  mount_uploader :card_image, AvatarUploader

  has_many :likes, as: :likeable
  has_many :dislikes, as: :dislikeable

  def rating
    self.likes.count - self.dislikes.count
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    unless params[:sort_by]
      @articles = Article.all
    else
      @articles = Article.sorted_by_likes
    end
  end

  def show
    @article = Article.friendly.find(params[:id])
  end
end

app/controllers/editor/articles_controller.rb
module Editor
  class ArticlesController < ApplicationController
    before_action :admin_user!
    before_action :set_article, only: [:edit, :update, :destroy]

    def index
      @articles = Article.all
    end

    def new
      @article = Article.new
    end

    def create
      @article = Article.new(article_params)

      if @article.save
        redirect_to editor_articles_path, notice: 'Article was successfully created!'
      else
        render :new
      end
    end

    def edit
    end

    def update
      if @article.update_attributes(article_params)
        redirect_to editor_articles_path, notice: 'Article was successfully updated!'
      else
        render :edit
      end
    end

    def destroy
      @article.destroy

      redirect_to editor_articles_path, notice: 'Article was successfully deleted!'
    end

    private

    def admin_user!
      return if current_user && current_user.admin?

      raise CanCan::AccessDenied
    end

    def set_article
      @article = Article.friendly.find(params[:id])
    end

    def article_params
      params.require(:article).permit(
        :title, :card_image, :body
      )
    end
  end
end

app/views/articles/index.html.haml
%h1.page-title Новости
.page--sort-box
  = link_to articles_path, class: 'page--sort-item' do
    По дате
    %svg.comments-sort--icon
      %use{"xlink:href" => "#{root_url}/image/icons/sprite.svg#descendant"}
  = link_to articles_path(sort_by: :likes), class: 'page--sort-item' do
    По популярности
    %svg.comments-sort--icon
      %use{"xlink:href" => "#{root_url}/image/icons/sprite.svg#descendant"}
.content--grid
  - @articles.each do |article|
    %a.grid--item.news-grid--item{:href => article_path(article)}
      %span.news-grid--label-box
        %span.news-grid--label{"data-palette" => "0"} WSOP
        %span.news-grid--date
          = I18n.l(article.created_at.in_time_zone('Moscow'), format: :short)
      %img.news-grid--image{:alt => "/", :src => article.card_image.url}/
      %span.news-grid--title
        = article.title.upcase
      %span.news-grid--subtitle
        = strip_tags(article.body).first(111) + '...'
      %span.news-grid--end-box
        %span.news-grid--end-button Читать
        %span.news-grid--end-data
          %span.news-grid--end-data-item
            %svg.news-grid--end-data-icon
              %use{"xlink:href" => "#{root_url}/image/icons/sprite.svg#comments"}
            %span.news-grid--end-data-text
              = article.comments.count

app/views/articles/show.html.haml
.content-main--cover
  .user-path--cover
    %a.user-path--item{:href => articles_path} Новости
    %a.user-path--item{:href => ""}
      = @article.title
  .news-inner-head--cover
    %p.news-inner-head--label{"data-palette" => "0"} WSOP
    %p.news-inner-head--date
      = I18n.l(@article.created_at.in_time_zone('Moscow'), format: :short)
    = button_to '+', likes_path(likeable_id: @article.id, likeable_type: 'Article'), method: :post, remote: true, class: 'comments-item--counter-action comments-item--counter-action-next', form: { id: 'article_like' }
    %span.ml-5#rating
      = @article.likes.count - @article.dislikes.count
    = button_to '-', dislikes_path(dislikeable_id: @article.id, dislikeable_type: 'Article'), method: :post, remote: true, class: 'comments-item--counter-action comments-item--counter-action-prev ml-5 mb-1', form: { id: 'article_dislike' }
  %h1
    = @article.title
  = @article.body.html_safe
  .comments--cover
    .comments-head--cover
      %p.comments-head--caption#comments_count
        = "#{@article.comments.count} комментариев:"
      .comments-sort--cover
        %button.comments-sort--item
          По дате
          %svg.comments-sort--icon
            %use{"xlink:href" => "#{root_url}/image/icons/sprite.svg#descendant"}
        %button.comments-sort--item
          По популярности
          %svg.comments-sort--icon
            %use{"xlink:href" => "#{root_url}/image/icons/sprite.svg#descendant"}
    .comments-body--cover#comments
      - @article.comments.each do |comment|
        .comments-item--cover
          .comments-item--info-box
            %p.comments-item--info-box-name
              = comment.user.nickname
            %img.comments-item--info-box-icon{:alt => "/", :src => "#{root_url}/image/example/avatar.svg"}/
            %a.comments-item--info-box-more{:href => profile_path(comment.user.nickname), :target => '_blank'} Профиль
          .comments-item--text-box
            .comments-item--text-box-head
              %p.comments-item--text-box-head-date
                = I18n.l(comment.created_at.in_time_zone('Moscow'), format: :short)
            .comments-item--text-box-body
              %p
                = comment.body
            .comments-item--text-box-foot
              .comments-item--text-box-foot-box
                .comments-item--counter--cover
                  = button_to '+', likes_path(likeable_id: comment.id, likeable_type: 'Comment'), method: :post, remote: true, class: 'comments-item--counter-action comments-item--counter-action-next', form: { id: 'comment_like' }
                  %span.ml-5#comment_rating
                    = comment.likes.count - comment.dislikes.count
                  = button_to '-', dislikes_path(dislikeable_id: comment.id, dislikeable_type: 'Comment'), method: :post, remote: true, class: 'comments-item--counter-action comments-item--counter-action-prev ml-5 mb-1', form: { id: 'comment_dislike' }
      %br
      - if current_user
        %form#comments-add.comments-add-message--cover{:action => comments_path(article_id: @article.id), :method => :post, "data-remote" => "true"}
          %p.comments-add-message--title Добавить комментарий
          %textarea.comments-add-message--field#comment_area{:name => "body"}
          %button.comments-add-message--submit{"data-button" => "red", :tupe => "submit"} Отправить
        %button.add-message--fix{"data-scroll-to" => "comments-add"}
      - else
        %p#comments-aswer.comments--variant
          Чтобы оставлять комментарии, вам необходимо
          %span.comments--variant-button.modal-call--entry Войти
          или
          %span.comments--variant-button.modal-call--reg-user Зарегистрироваться
:javascript
  $(document).ready(function() {
    $('#comments')
    .bind('ajax:success', function(evt, data, status, xhr) {
      prev_value = parseInt($('#comments_count').text())
      $('#comments_count').text(prev_value + 1 + ' комментариев:')
      $("#comment_area").val('');
    })
    $('#article_like')
    .bind('ajax:success', function(evt, data, status, xhr) {
      prev_value = parseInt($('#rating').text())
      $('#rating').text(prev_value + 1)
    })
    $('#article_dislike')
    .bind('ajax:success', function(evt, data, status, xhr) {
      $('#rating').text(parseInt($('#rating').text()) -1)
    })
    $('#comment_like')
    .bind('ajax:success', function(evt, data, status, xhr) {
      prev_value = parseInt($('#comment_rating').text())
      $('#comment_rating').text(prev_value + 1)
    })
    $('#comment_dislike')
    .bind('ajax:success', function(evt, data, status, xhr) {
      $('#comment_rating').text(parseInt($('#comment_rating').text()) -1)
    })
  });