config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'pages#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :tournaments, only: [:index, :show] do
    put 'register_player'
  end
  resources :streams, only: [:index]
  resources :articles, only: [:index, :show]

  namespace :dashboard do
    resources :tournaments, only: [:index, :show]
  end

  namespace :editor do
    resources :articles
    resources :tournaments
  end

  resources :likes, only: [:create]
  resources :dislikes, only: [:create]
  resources :comments, only: [:create]

  mount Thredded::Engine => '/forum'

  get 'contacts', to: 'pages#contacts'
  get 'profile/:slug', to: 'profiles#show', as: :profile
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)

    if user.admin?
      can :access, :rails_admin
      can :manage, :all
    else
      can :read, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  default_scope { order('id DESC') }
  
  scope :sorted_by_likes, -> { unscoped.all.includes(:comments).sort {|a, b| b.rating <=> a.rating } }

  extend FriendlyId
  friendly_id :title, use: :slugged

  has_many :comments

  mount_uploader :card_image, AvatarUploader

  has_many :likes, as: :likeable
  has_many :dislikes, as: :dislikeable

  def rating
    self.likes.count - self.dislikes.count
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  default_scope { order('id DESC') }
  
  belongs_to :article
  belongs_to :user

  has_many :likes, as: :likeable
  has_many :dislikes, as: :dislikeable
end

app/models/dislike.rb
class Dislike < ApplicationRecord
  belongs_to :dislikeable, polymorphic: true
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :likeable, polymorphic: true
  belongs_to :user
end

app/models/stream.rb
class Stream < ApplicationRecord
  belongs_to :user

  enum status: [:draft, :published]

  scope :present, -> { where.not(link: nil).where.not(link: '') }
  scope :online, -> { present.where(status: :published) }
end

app/models/tournament.rb
class Tournament < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  has_and_belongs_to_many :players, class_name: 'User'

  mount_uploader :avatar, AvatarUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, uniqueness: true

  enum role: [:player, :admin]

  has_one :stream
  has_many :comments
  has_many :likes
  has_many :dislikes
  has_and_belongs_to_many :tournaments

  accepts_nested_attributes_for :stream

  def admin
    self.admin?
  end

  def name
    self.nickname
  end

  class << self
    def find_by_slug!(slug)
      User.find_by!(nickname: slug)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to main_app.root_path, alert: 'У вас нет прав для просмотра этой страницы.'
  end

  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  protected

  def configure_permitted_parameters
    attrs = [:nickname, :email, :password, :password_confirmation, :remember_me, stream_attributes: {}]

    devise_parameter_sanitizer.permit :sign_up, keys: attrs
    devise_parameter_sanitizer.permit :account_update, keys: attrs
  end

  private

  def record_not_found
    render plain: 'Not found!'
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    unless params[:sort_by]
      @articles = Article.all
    else
      @articles = Article.sorted_by_likes
    end
  end

  def show
    @article = Article.friendly.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @comment = Article.find(params[:article_id]).comments.new(user_id: current_user.id, body: params[:body])

    respond_to do |format|
      if @comment.save
        format.js
      end
    end
  end
end

app/controllers/dislikes_controller.rb
class DislikesController < ApplicationController
  def create
    if current_user.nil? || Dislike.where(dislikeable_id: params[:dislikeable_id], dislikeable_type: params[:dislikeable_type], user: current_user).any?
      render json: 'error', status: :unprocessable_entity
    else
      dislike = Dislike.create!(dislikeable_id: params[:dislikeable_id], dislikeable_type: params[:dislikeable_type], user: current_user)
      render json: dislike.to_json, status: :ok
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    if current_user.nil? || Like.where(likeable_id: params[:likeable_id], likeable_type: params[:likeable_type], user: current_user).any?
      render json: 'error', status: :unprocessable_entity
    else
      like = Like.create!(likeable_id: params[:likeable_id], likeable_type: params[:likeable_type], user: current_user)
      render json: like.to_json, status: :ok
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @tournament = Tournament.last
    @streams = Stream.online
    @articles = Article.last(2)
  end

  def contacts
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @profile = User.find_by_slug!(params[:slug])
  end
end

app/controllers/streams_controller.rb
class StreamsController < ApplicationController
  def index
    @streams = Stream.online
  end
end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  before_action :authenticate_user!, only: [:register_player]

  def index
    @tournaments = Tournament.all
  end

  def show
    @tournament = Tournament.friendly.find(params[:id])
  end

  def register_player
    @tournament = Tournament.friendly.find(params[:tournament_id])

    if @tournament.players.count >= (@tournament.max_players || 9999)
      redirect_to @tournament, alert: 'Достигнуто максимальное количество участников!'
    elsif @tournament.players.include?(current_user)
      redirect_to dashboard_tournament_path(@tournament), alert: 'Вы уже зарегистрировались в турнире!'
    else
      @tournament.players << current_user
      @tournament.save

      redirect_to dashboard_tournament_path(@tournament), notice: 'Вы успешно зарегистрировались в турнире!'
    end
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create
    resource = User.find_for_database_authentication(email: params[:user][:email])
    return invalid_login_attempt unless resource
  
    if resource.valid_password?(params[:user][:password])
      sign_in :user, resource
      set_flash_message(:notice, :signed_in)
      return render body: nil
    end
  
    invalid_login_attempt
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  def invalid_login_attempt
    set_flash_message(:alert, :invalid)
    render json: flash[:alert], status: 401
  end
  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def dashboard_path?
    request.path =~ /dashboard/
  end

  def messages_path?
    request.path =~ /messages/ || request.path =~ /private-topics/
  end

  def forum_path?
    request.path =~ /forum/
  end

  def articles_path?
    request.path =~ /articles/
  end

  def contacts_path?
    request.path =~ /contacts/
  end

  def streams_path?
    request.path =~ /streams/
  end

  def tournaments_path?
    request.path =~ /tournaments/
  end

  def resource_name
    :user
  end
 
  def resource
    @resource ||= User.new
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title GAshow
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all'
    %link{:href => "#{root_url}/css/all.css", :rel => "stylesheet"}/
    %script{src: "#{root_url}/js/Swiper.slider.4.5.0.min.js"}
    %script{src: "#{root_url}/js/webcore.full.1.0.0.min.js"}
    %script{src: "#{root_url}/js/webcore.frontend.js"}
    = javascript_include_tag 'application'
  %body
    = render 'shared/navbar'
    .content--cover.container
      = render 'shared/aside'
      .content
        = render 'shared/flash_messages'
        = yield
    = render 'shared/footer'

app/views/shared/_aside.haml
%aside.aside--cover
  .menu--list-cover
    .menu--list
      %a.menu--item{href: tournaments_path, class: ('active-node' if tournaments_path?)} Турниры
      %a.menu--item{href: articles_path, class: ('active-node' if articles_path?)} Новости
      %a.menu--item{href: streams_path, class: ('active-node' if streams_path?)} Стримы игроков
      %a.menu--item{href: '/forum', class: ('active-node' if forum_path?)} Форум
      %a.menu--item{href: contacts_path, class: ('active-node' if contacts_path?)} Контакты

app/views/shared/_flash_messages.haml
- if notice
  %ul
    %li
      = notice
- if alert
  %ul
    %li
      = alert

app/views/shared/_footer.haml
%footer.footer--cover
  .footer--container.container
    .footer--logo-box
      %a.footer--logo-cover{:href => "index.html"}
        %img.footer--logo-icon{:alt => "/", :src => "#{root_url}/image/icons/logo/small.svg"}/
      %p.footer--logo-copy Copyright © GShow 2020
    .social--cover
      %a.social--item{:href => "tg://resolve?domain=swan4", :target => "_blank"}
        %svg.social--icon
          %use{"xlink:href" => "#{root_url}/image/icons/sprite.svg#telegram"}
      %a.social--item{:href => "https://www.twitch.tv/swan4", :target => "_blank"}
        %svg.social--icon
          %use{"xlink:href" => "#{root_url}/image/icons/sprite.svg#twitch"}
      %a.social--item{:href => "https://www.instagram.com/swan4poker/", :target => "_blank"}
        %svg.social--icon
          %use{"xlink:href" => "#{root_url}/image/icons/sprite.svg#insta"}
      %a.social--item{:href => "https://www.youtube.com/channel/UC2h3-ZCKW8rEVBcDaBua7KA", :target => "_blank"}
        %svg.social--icon
          %use{"xlink:href" => "#{root_url}/image/icons/sprite.svg#youtube"}
%div{"data-webcore--modal-id" => "entry"}
  %p.modal--caption Вход
  %form.modal-form--cover#loginForm{action: user_session_path, method: 'post', 'data-remote': 'true'}
    %input{:name => "hidden", :type => "hidden", :value => "вход"}/
    %input.modal-form--input{:name => "user[email]", :placeholder => "E-mail", :type => "text"}/
    %input.modal-form--input{:name => "user[password]", :placeholder => "Пароль", :type => "password"}/
    .modal-form--box
      %label.modal-form--label
        %input.modal-form--checkbox{:name => "user[remember_me]", :checked => "checked", :type => "checkbox"}/
        %span.modal-form--checkbox-text Запомнить меня
      %button.modal-form--restore{:type => "button"} Забыли пароль?
    %button.modal-form--submit{"data-button" => "red", :type => "submit"} Войти в аккаунт
    %p.modal-form--question
      Еще нет аккаунта?
      %span.modal-form--question-inner.modal-call--reg-user-hide Регистрация
%div{"data-webcore--modal-id" => "reg-user"}
  %p.modal--caption Регистрация
  %form.modal-form--cover#regForm{action: user_registration_path, method: 'post', 'data-remote': 'true'}
    %input{:name => "hidden", :type => "hidden", :value => "регистрация"}/
    %input.modal-form--input{:name => "user[nickname]", :placeholder => "Никнейм", :type => "text"}/
    %input.modal-form--input{:name => "user[email]", :placeholder => "E-mail", :type => "text"}/
    %input.modal-form--input{:name => "user[password]", :placeholder => "Пароль", :type => "password"}/
    %input.modal-form--input{:name => "user[password_confirmation]", :placeholder => "Повторите пароль", :type => "password"}/
    %p.modal-form--agreement
      Нажимая кнопку "Зарегистрироваться" я подверждаю, что ознакомлен и согласен с
      %span.modal-form--agreement-open.modal-call--agreement Политикой конфиденциальности
    %button.modal-form--submit{"data-button" => "red", :type => "submit"} Зарегистрироваться
    %p.modal-form--question
      Уже есть аккаунт?
      %span.modal-form--question-inner.modal-call--entry-hide Выполните вход
%div{"data-webcore--modal-id" => "reg-tourn"}
  - current_tournament = @tournament if defined? @tournament
  - current_tournament = current_tournament || tournament if defined? tournament
  - current_tournament = current_tournament || Tournament.last
  %p.modal--caption Регистрация на турнир
  %p.modal--text
    Вы регистрируетесь на турнир
    %strong.modal--tourn-name 
      = "PokerOK #{current_tournament.name}"
  %form.modal-form--cover{:action => "/"}
    %input{:name => "hidden", :type => "hidden", :value => "регистрация на турнир"}/
    = link_to 'Подтвердить', tournament_register_player_path(tournament_id: current_tournament.id), class: 'modal-form--submit', method: :put, 'data-button': 'red'
    %button.modal-form--cancel.modal-form--question-inner{:type => "button"} Отмена
%div{"data-webcore--modal-id" => "restore"}
  %p.modal--caption Восстановление пароля
  %p.modal--text Введите e-mail
  %form.modal-form--cover{:action => "/"}
    %input.modal-form--input{:name => "email", :placeholder => "E-mail", :type => "text"}/
    %input{:name => "hidden", :type => "hidden", :value => "Восстановление пароля"}/
    %button.modal-form--submit{"data-button" => "red", :type => "submit"} Подтвердить
    %button.modal-form--cancel.modal-form--question-inner{:type => "button"} Отмена

:javascript
  $(document).ready(function() {
    $('#loginForm')
    .bind('ajax:success', function(evt, data, status, xhr) {
      location.reload();
    })
    .bind("ajax:error", function(evt, xhr, status, error) {
      console.log('Invalid email or password');
    });
    $('#regForm')
    .bind('ajax:success', function(evt, data, status, xhr) {
      location.reload();
    })
    .bind("ajax:error", function(evt, xhr, status, error) {
      console.log('Error while registration');
    });
  });

app/views/shared/_navbar.haml
%header.header--cover
  .header--sticky
    .container.header--container
      %a.header--logo-cover{href: root_path}
        %img.header--logo-icon{:alt => "/", :src => "#{root_url}/image/icons/logo/small.svg"}/
      .autoriz--box-cover
        - if current_user
          .autoriz--cover
            %a.autoriz--item.autoriz--home{:href => dashboard_tournaments_path}
              %svg.autoriz--icon>
                %use{"xlink:href" => "#{root_url}/image/icons/sprite.svg#champion"}
              Игровой кабинет
            %a.autoriz--item.autoriz--message{:href => 'forum/private-topics'}
              %svg.autoriz--icon
                %use{"xlink:href" => "#{root_url}/image/icons/sprite.svg#comment"}
              // %span.autoriz--message-count 5
            .autoriz--item.autoriz-user--cover
              %a.autoriz-user--home{:href => profile_path(current_user.nickname)}
                %svg.autoriz--icon>
                  %use{"xlink:href" => "#{root_url}/image/icons/sprite.svg#name"}
                = current_user.nickname
              %button.autoriz-user--switch
                %svg.autoriz-user--switch-icon
                  %use{"xlink:href" => "#{root_url}/image/icons/sprite.svg#arrow.v1.down"}
              .autoriz-user--select
                = link_to 'Настройки', edit_user_registration_path, class: 'autoriz-user--option'
                = link_to 'Профиль', profile_path(current_user.nickname), class: 'autoriz-user--option'
                = link_to 'Выйти', destroy_user_session_path, class: 'autoriz-user--option', "data-method": :delete
        - else
          .autoriz-not--cover
            %button.autoriz-not--item.modal-call--entry
              Войти
              %svg.autoriz-not--icon
                %use{"xlink:href" => "#{root_url}/image/icons/sprite.svg#login"}
            %button.autoriz-not--item.modal-call--reg-user Регистрация