config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'pages#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :tournaments, only: [:index, :show] do
    put 'register_player'
  end
  resources :streams, only: [:index]
  resources :articles, only: [:index, :show]

  namespace :dashboard do
    resources :tournaments, only: [:index, :show]
  end

  namespace :editor do
    resources :articles
    resources :tournaments
  end

  resources :likes, only: [:create]
  resources :dislikes, only: [:create]
  resources :comments, only: [:create]

  mount Thredded::Engine => '/forum'

  get 'contacts', to: 'pages#contacts'
  get 'profile/:slug', to: 'profiles#show', as: :profile
end

app/models/article.rb
class Article < ApplicationRecord
  default_scope { order('id DESC') }
  
  scope :sorted_by_likes, -> { unscoped.all.includes(:comments).sort {|a, b| b.rating <=> a.rating } }

  extend FriendlyId
  friendly_id :title, use: :slugged

  has_many :comments

  mount_uploader :card_image, AvatarUploader

  has_many :likes, as: :likeable
  has_many :dislikes, as: :dislikeable

  def rating
    self.likes.count - self.dislikes.count
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    unless params[:sort_by]
      @articles = Article.all
    else
      @articles = Article.sorted_by_likes
    end
  end

  def show
    @article = Article.friendly.find(params[:id])
  end
end

app/controllers/editor/articles_controller.rb
module Editor
  class ArticlesController < ApplicationController
    before_action :admin_user!
    before_action :set_article, only: [:edit, :update, :destroy]

    def index
      @articles = Article.all
    end

    def new
      @article = Article.new
    end

    def create
      @article = Article.new(article_params)

      if @article.save
        redirect_to editor_articles_path, notice: 'Article was successfully created!'
      else
        render :new
      end
    end

    def edit
    end

    def update
      if @article.update_attributes(article_params)
        redirect_to editor_articles_path, notice: 'Article was successfully updated!'
      else
        render :edit
      end
    end

    def destroy
      @article.destroy

      redirect_to editor_articles_path, notice: 'Article was successfully deleted!'
    end

    private

    def admin_user!
      return if current_user && current_user.admin?

      raise CanCan::AccessDenied
    end

    def set_article
      @article = Article.friendly.find(params[:id])
    end

    def article_params
      params.require(:article).permit(
        :title, :card_image, :body
      )
    end
  end
end

app/controllers/editor/tournaments_controller.rb
module Editor
  class TournamentsController < ApplicationController
    before_action :admin_user!
    before_action :set_tournament, except: [:index]

    def index
      @tournaments = Tournament.all
    end

    def edit
    end

    def update
      if @tournament.update_attributes(tournament_params)
        redirect_to editor_tournaments_path, notice: 'Tournament rules was updated!'
      else
        render :edit
      end
    end

    private

    def admin_user!
      return if current_user && current_user.admin?

      raise CanCan::AccessDenied
    end

    def set_tournament
      @tournament = Tournament.friendly.find(params[:id])
    end

    def tournament_params
      params.require(:tournament).permit(
        :rules
      )
    end
  end
end

app/views/editor/articles/_article.html.haml
%tr.info
  %td.text-center
    = article.title
  %td.text-center
    = image_tag article.card_image.url, width: '200px', height: '150px'
  %td.text-center
    = link_to 'Edit', edit_editor_article_path(article), class: 'btn-warning'
  %td.text-center
    = link_to 'Delete', editor_article_path(article), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn-danger'

app/views/editor/articles/_form.html.haml
- url = editor_articles_path
- url = editor_article_path(@article) if controller.action_name == 'edit'
= simple_form_for @article, url: url do |f|
  = f.label :title
  %br
  = f.input :title, label: false, input_html: { class: 'article_title' }
  %br
  = f.input :card_image
  %br
  = f.input :body, as: :text, label: false, input_html: { class: 'tinymce', rows: 40, cols: 120 }
  = tinymce
  %br
  = f.button :submit, class: 'btn-success'

app/views/editor/articles/edit.html.haml
.user-path--cover
  %a.user-path--item{:href => editor_articles_path} Новости
  %a.user-path--item{:href => ""}
    = @article.title
%br
%br
.center
  = render 'editor/articles/form'

app/views/editor/articles/index.html.haml
.user-path--cover
  %a.user-path--item{:href => editor_articles_path} Новости

= link_to 'Создать', new_editor_article_path, class: 'btn-success'

%table.table.table-bordered.table-hover
  %tr.active
    %th
      %h4.text-center Title
    %th
      %h4.text-center Image
    %th{colspan: 2}
      %h4.text-center Actions
  = render @articles

app/views/editor/articles/new.html.haml
.user-path--cover
  %a.user-path--item{:href => editor_articles_path} Новости
  %a.user-path--item{:href => ""} Создать
%br
%br
.center
  = render 'editor/articles/form'